import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className='h-full' lang="en">
      <body className="bg-black h-full text-white">
        <ReduxProvider>
          <div className="h-full">
          <Header/>
            <main className="pt-[100px] h-full">{children}</main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
